# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MORTAL_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QMovie
import sys

class Ui_MORTALUi(object):
    def setupUi(self, MORTALUi):
        MORTALUi.setObjectName("MORTALUi")
        #MORTALUi.resize(1459, 884)
        MORTALUi.resize(1059, 666)
        #MORTALUi.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MORTALUi)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        #self.label.setGeometry(QtCore.QRect(10, 0, 1441, 821))
        self.label.setGeometry(QtCore.QRect(0, 0, 1061, 671))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("mortal bg.gif"))
        self.Movie=QMovie("mortal bg.gif")
        self.label.setMovie(self.Movie)
        self.Movie.start()
        self.label.setScaledContents(True)
        self.label.setObjectName("label1")


        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(65, 270, 401, 281))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("Earth.gif"))
        self.Movie=QMovie("Earth.gif")
        self.label_3.setMovie(self.Movie)
        self.Movie.start()
        self.label_3.setScaledContents(True)
        
        self.label_3.setObjectName("label_3")

        MORTALUi.setCentralWidget(self.centralwidget)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton.setGeometry(QtCore.QRect(950, 720, 93, 28))
        self.pushButton.setGeometry(QtCore.QRect(840, 620, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        #self.pushButton_2.setGeometry(QtCore.QRect(1040, 720, 93, 28))
        self.pushButton_2.setGeometry(QtCore.QRect(930, 620, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        #self.label_2.setGeometry(QtCore.QRect(50, 470, 461, 321))
        self.label_2.setGeometry(QtCore.QRect(10, 10, 401, 91))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("initializing.gif"))
        self.Movie=QMovie("initializing.gif")
        self.label_2.setMovie(self.Movie)
        self.Movie.start()
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        #self.textBrowser.setGeometry(QtCore.QRect(590, 20, 211, 41))
        self.textBrowser.setGeometry(QtCore.QRect(590, 20, 211, 41))
        font = QtGui.QFont()
        font.setFamily("nirmal UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        #self.textBrowser_2.setGeometry(QtCore.QRect(820,20, 211, 41))
        self.textBrowser_2.setGeometry(QtCore.QRect(810,20, 211, 41))
        font = QtGui.QFont()
        font.setFamily("nirmal UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.textBrowser_2.setFont(font)
        self.textBrowser_2.setStyleSheet("background:transparent;\n"
"border-radius:none;\n"
"color:white;\n"
"font-size:20px;")
        self.textBrowser_2.setObjectName("textBrowser_2")
        MORTALUi.setCentralWidget(self.centralwidget)
        self.retranslateUi(MORTALUi)
        QtCore.QMetaObject.connectSlotsByName(MORTALUi)

        # self.menubar = QtWidgets.QMenuBar(MORTAL_UI)
        # self.menubar.setGeometry(QtCore.QRect(0, 0, 1459, 26))
        # self.menubar.setObjectName("menubar")
        # MORTAL_UI.setMenuBar(self.menubar)
        # self.statusbar = QtWidgets.QStatusBar(MORTAL_UI)
        # self.statusbar.setObjectName("statusbar")
        # MORTAL_UI.setStatusBar(self.statusbar)

        

    def retranslateUi(self, MORTAL_Ui):
        _translate = QtCore.QCoreApplication.translate
        MORTAL_Ui.setWindowTitle(_translate("MORTALUi", "MainWindow"))
        self.pushButton.setText(_translate("MORTALUi", "START"))
        self.pushButton_2.setText(_translate("MORTALUi", "STOP"))
        


if __name__ == "__main__":
    
    app = QtWidgets.QApplication(sys.argv)
    MORTALUii = QtWidgets.QMainWindow()
    ui = Ui_MORTALUi()
    ui.setupUi(MORTALUii)
    MORTALUii.show()
    sys.exit(app.exec_())
